"use client";

import {
  AlignLeft,
  ArrowDown,
  ArrowDownAZ,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  AtSign,
  Award,
  Baby,
  BadgeCheck,
  Bell,
  BookOpen,
  BookOpenText,
  BookPlus,
  BookText,
  Bookmark,
  Bot,
  Brain,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  ChartNoAxesColumn,
  ChartPie,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlay,
  CirclePlus,
  CircleX,
  Clapperboard,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Coffee,
  Compass,
  Copy,
  Disc3,
  Download,
  Ellipsis,
  EllipsisVertical,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  Feather,
  FileUp,
  Film,
  Flame,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderSymlink,
  FolderX,
  Folders,
  Footprints,
  Frown,
  Funnel,
  Gamepad,
  Gamepad2,
  Gavel,
  Gem,
  Globe,
  Grid3x3,
  Hand,
  Heart,
  History,
  Hourglass,
  House,
  Image,
  ImagePlus,
  Images,
  Infinity,
  Info,
  KeyRound,
  Landmark,
  Laugh,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Library,
  LibraryBig,
  Link,
  List,
  ListFilter,
  ListOrdered,
  ListPlus,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Medal,
  Menu,
  MessageSquareText,
  Minus,
  Moon,
  Mountain,
  NotebookPen,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  Puzzle,
  Pipette,
  Play,
  Plus,
  Pointer,
  QrCode,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  Shapes,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sofa,
  Sparkle,
  Sparkles,
  Square,
  SquareCheck,
  SquareMinus,
  Star,
  ScanBarcode,
  Gift,
  Sun,
  TrendingDown,
  SunMoon,
  Swords,
  Tag,
  ThumbsDown,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  Type,
  Undo2,
  User,
  UserMinus,
  UserPlus,
  UserSearch,
  UserX,
  Users,
  Volleyball,
  Wallet,
  WifiOff,
  Wine,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

import { useEffect } from "react";

import { cn } from "../lib/utils";
import { useUIKit } from "../provider";

/**
 * Nomi Material Icons → icone Lucide.
 *
 * L'app usa i nomi Material in tutti i componenti (eredità di <mat-icon>
 * dell'app Angular). Prima ognuno era una legatura del font "Material Icons"
 * scaricato da Google con `display=block`: finché il font non arrivava
 * (rete lenta, CDN bloccato, primo avvio offline) le icone restavano vuote.
 * Ora sono SVG inclusi nel bundle: compaiono subito e funzionano offline.
 *
 * I chiamanti non cambiano: stesso `name`, e la dimensione continua a
 * seguire il font-size (`!text-[20px]`) perché l'SVG misura 1em. I nomi
 * non mappati ripiegano sul font, così nessuna icona sparisce.
 */
const ICONS: Record<string, LucideIcon> = {
  account_balance: Landmark,
  add: Plus,
  add_circle: CirclePlus,
  add_photo_alternate: ImagePlus,
  album: Disc3,
  all_inclusive: Infinity,
  alternate_email: AtSign,
  analytics: ChartColumn,
  insights: ChartLine,
  travel_explore: Compass,
  redeem: Gift,
  trending_down: TrendingDown,
  qr_code_scanner: ScanBarcode,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  auto_awesome: Sparkles,
  auto_stories: BookOpen,
  bar_chart: ChartColumn,
  bolt: Zap,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  cancel: CircleX,
  category: Shapes,
  celebration: PartyPopper,
  check: Check,
  check_box: SquareCheck,
  check_box_outline_blank: Square,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  child_care: Baby,
  clear: X,
  close: X,
  cloud_download: CloudDownload,
  cloud_queue: Cloud,
  cloud_upload: CloudUpload,
  coffee: Coffee,
  colorize: Pipette,
  compare_arrows: ArrowLeftRight,
  content_copy: Copy,
  create_new_folder: FolderPlus,
  brightness_auto: SunMoon,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  delete: Trash2,
  delete_outline: Trash2,
  diamond: Gem,
  directions_car: Car,
  directions_run: Footprints,
  done_all: CheckCheck,
  donut_large: ChartPie,
  donut_small: ChartPie,
  download: Download,
  edit: Pencil,
  edit_note: NotebookPen,
  emoji_events: Trophy,
  error_outline: CircleAlert,
  euro: Euro,
  event: CalendarDays,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  explore: Compass,
  extension: Puzzle,
  face: Smile,
  favorite: Heart,
  favorite_border: Heart,
  filter_alt: Funnel,
  filter_list: ListFilter,
  folder: Folder,
  folder_copy: Folders,
  folder_off: FolderX,
  folder_open: FolderOpen,
  folder_shared: FolderSymlink,
  format_list_numbered: ListOrdered,
  front_hand: Hand,
  gamepad: Gamepad,
  gavel: Gavel,
  grid_on: Grid3x3,
  grid_view: LayoutGrid,
  group: Users,
  groups: Users,
  help_outline: CircleHelp,
  help: CircleHelp,
  history: History,
  history_edu: Feather,
  home: House,
  hourglass_empty: Hourglass,
  image: Image,
  import_contacts: BookOpenText,
  indeterminate_check_box: SquareMinus,
  info: Info,
  install_mobile: Smartphone,
  inventory: Package,
  inventory_2: Package,
  label: Tag,
  landscape: Mountain,
  language: Globe,
  leaderboard: ChartNoAxesColumn,
  library_add: BookPlus,
  library_books: Library,
  light_mode: Sun,
  link: Link,
  list: List,
  live_tv: Tv,
  local_bar: Wine,
  local_fire_department: Flame,
  local_library: LibraryBig,
  local_offer: Tag,
  local_police: ShieldCheck,
  local_shipping: Truck,
  lock_outline: Lock,
  lock_reset: KeyRound,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  mail_outline: Mail,
  menu: Menu,
  menu_book: BookText,
  military_tech: Medal,
  mood_bad: Frown,
  more_horiz: Ellipsis,
  more_vert: EllipsisVertical,
  movie: Film,
  movie_filter: Clapperboard,
  new_releases: Sparkle,
  notifications: Bell,
  open_in_new: ExternalLink,
  palette: Palette,
  payments: Wallet,
  people: Users,
  person: User,
  person_add: UserPlus,
  person_outline: User,
  person_off: UserX,
  person_remove: UserMinus,
  person_search: UserSearch,
  pets: PawPrint,
  photo_camera: Camera,
  photo_library: Images,
  pie_chart: ChartPie,
  play_arrow: Play,
  play_circle: CirclePlay,
  playlist_add: ListPlus,
  psychology: Brain,
  public: Globe,
  qr_code: QrCode,
  rate_review: MessageSquareText,
  refresh: RefreshCw,
  remove: Minus,
  rocket_launch: Rocket,
  save: Save,
  schedule: Clock,
  search: Search,
  send: Send,
  sentiment_very_satisfied: Laugh,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  shuffle: Shuffle,
  smart_toy: Bot,
  sort: ArrowUpDown,
  sort_by_alpha: ArrowDownAZ,
  sports_esports: Gamepad2,
  sports_martial_arts: Swords,
  sports_soccer: Volleyball,
  star: Star,
  star_border: Star,
  stars: Award,
  subject: AlignLeft,
  swap_horiz: ArrowLeftRight,
  sync: RefreshCw,
  thumb_down: ThumbsDown,
  timer: Timer,
  title: Type,
  touch_app: Pointer,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  undo: Undo2,
  upload_file: FileUp,
  verified: BadgeCheck,
  view_list: LayoutList,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: TriangleAlert,
  weekend: Sofa,
  wifi_off: WifiOff,
  workspace_premium: Award,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
};

/** Icone che in Material sono piene: le stelle del voto e il cuore dei desideri. */
const FILLED = new Set(["star", "favorite"]);

export function Icon({ name, className }: { name: string; className?: string }) {
  const { icons } = useUIKit();
  const Svg = icons[name] ?? ICONS[name];
  if (!Svg) {
    return (
      <span className={cn("material-icons select-none", className)} aria-hidden="true">
        {name}
      </span>
    );
  }
  return (
    <span className={cn("material-icons app-icon select-none", className)} aria-hidden="true">
      <Svg className="size-[1em]" strokeWidth={2} fill={FILLED.has(name) ? "currentColor" : "none"} />
    </span>
  );
}

/**
 * Carica il font Material Icons dopo il primo render, solo come ripiego
 * per eventuali nomi non presenti in ICONS. Non blocca più la pagina.
 */
export function IconFontFallback() {
  useEffect(() => {
    if (document.querySelector("link[data-material-icons]")) return;
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = "https://fonts.googleapis.com/icon?family=Material+Icons&display=swap";
    link.dataset.materialIcons = "";
    document.head.appendChild(link);
  }, []);
  return null;
}
